# Generated by Django 3.2.4 on 2021-08-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=40)),
                ('text', models.TextField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('plot', models.TextField(max_length=100)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
