# Generated by Django 3.2.4 on 2021-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testt',
            fields=[
                ('testy', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
