# Generated by Django 3.2.4 on 2021-08-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_testt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testt',
        ),
    ]
