# Generated by Django 3.2.4 on 2021-08-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_delete_testt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
    ]
